import React, { ReactNode } from "react";

import type { Metadata } from "next";
import { Fredoka, Nunito } from "next/font/google";

import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fuzzy Hub",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => (
  <html lang="en" className={`${nunito.variable} ${fredoka.variable}`}>
    <body className="font-sans antialiased">{children}</body>
  </html>
);

export default RootLayout;
